apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sync-values
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  info: |
    This ConfigMap is used to store metadata about the value sync.
    It doesn't contain any actual secret data.
    
    Last Sync Time: {{ now | date "2006-01-02T15:04:05Z07:00" }}
    
    Infrastructure Values:
    - Database Enabled: {{ .Values.infrastructure.database.enabled }}
    - RabbitMQ Enabled: {{ .Values.infrastructure.rabbitmq.enabled }}
    
    Spring Boot Backend values (sb):
    - Replicas: {{ .Values.sb.replicaCount }}
    - Image: {{ .Values.sb.image.repository }}:{{ .Values.sb.image.tag }}
    
    Nginx Frontend values (nf):
    - Replicas: {{ .Values.nf.replicaCount }}
    - Image: {{ .Values.nf.image.repository }}:{{ .Values.nf.image.tag }} 