name: hello-world
region: eu-west-2
k8s_path: "./helm-charts"

# Services to deploy
services:
  - name: springboot-backend
    image: dstar55/docker-hello-world-spring-boot:latest
    port: 8080
    replicas: 1
    expose: true
  
  - name: nginx-frontend
    image: nginx:alpine
    port: 80
    replicas: 1
    expose: true
    configMapData:
      nginx.conf: |
        server {
            listen 80;
            server_name localhost;
            
            location / {
                proxy_pass http://springboot-backend:8080;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    volumeMounts:
      - name: nginx-config
        mountPath: /etc/nginx/conf.d/default.conf
        subPath: nginx.conf
    volumes:
      - name: nginx-config
        configMap:
          name: nginx-frontend-config
          items:
            - key: nginx.conf
              path: nginx.conf

# Infrastructure dependencies
dependencies:
  - type: database
    provider: postgres
    version: "13"
    storage: 20
    instance_class: db.t3.small
  
  - type: queue
    provider: RabbitMQ
    version: "3.13"
    auto_minor_version_upgrade: true
    instance_class: mq.t3.micro 