apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-frontend.fullname" . }}-config
  labels:
    {{- include "nginx-frontend.labels" . | nindent 4 }}
data:
  nginx.conf: |
    {{- .Values.configMapData.nginx.conf | nindent 4 }}