# Global values
global:
  domain: buildandburn.local

# Default values for parent chart
nameOverride: ""
fullnameOverride: ""

# Infrastructure information
infrastructure:
  database:
    enabled: true
    host: ""
    port: 5432
    name: ""
  rabbitmq:
    enabled: true
    host: ""
    port: 5672

# Spring Boot Backend values (sb is the alias for springboot-backend)
sb:
  replicaCount: 1
  image:
    repository: dstar55/docker-hello-world-spring-boot
    tag: latest
  service:
    port: 8080
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: api.buildandburn.local
        paths:
          - path: /
            pathType: Prefix
  # These values will be populated from infrastructure if available
  database:
    host: ""
    port: 5432
    name: ""
  rabbitmq:
    host: ""
    port: 5672
  livenessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5

# Nginx Frontend values (nf is the alias for nginx-frontend)
nf:
  replicaCount: 1
  image:
    repository: nginx
    tag: alpine
  service:
    port: 80
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: www.buildandburn.local
        paths:
          - path: /
            pathType: Prefix
  configMapData:
    nginx.conf: |
      server {
          listen 80;
          server_name localhost;
          
          location / {
              proxy_pass http://{{ .Release.Name }}-sb:8080;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }
  volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: nginx.conf
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-frontend-config
        items:
          - key: nginx.conf
            path: nginx.conf
  livenessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5 